apiVersion: v1
kind: Service
metadata:
  name: classic-load-balancer-external-service
spec:
  type: LoadBalancer
  selector:
    app: my-product-service-pod
  ports:
    - name: product-service-ports
      protocol: TCP
      port: 80
      targetPort: 8080 #where application internally runs
