apiVersion: v1
kind: Service
metadata:
 name: eks-rds-mysql-service #Microservice uses this name to get it connected to RDS
spec:
 type: ExternalName
 externalName: productdb.ctxw7exwnldw.ap-south-1.rds.amazonaws.com
 ports:
   - port: 3306 #where container is actually running
     targetPort: 3306 #port of this service. Cluster members talk via this port
